version: '3'

services:
   mongo:
      container_name: location_db
      image: mongo:latest
      volumes:
         - ./mongo:/data/db
      ports:
         - 27017:27017
   
   simulator:
      container_name: bus_simulator
      image: python:3.7
      environment:
         - MONGO_URI=mongodb://mongo:27017/
         - LOC_SPAWN_INTERVAL=5
         - LOC_TTL=10
         - DRY_RUN=true
      volumes:
        - ./bus-sim.py:/bus-sim.py
        - ./paradas.json:/paradas.json
        - ./locs.csv:/locs.csv
      command: ["python3", "bus-sim.py"]

  