version: '3'

services:
   mongo:
      container_name: location_db
      image: mongo:latest
      volumes:
         - ./mongo:/data/db
      ports:
         - 27017:27017
   
   exporter:
      container_name: loc_exporter
      image: python:3.7
      environment:
         - MONGO_URI=mongodb://mongo:27017/
         - FIREBASE_URI=https://bus-stop-system-default-rtdb.europe-west1.firebasedatabase.app/
         - SPEED=10
         - UPDATE=5
      volumes:
         - ./loc-exporter.py:/loc-exporter.py
         - ./keys:/keys
         - ./paradas.json:/paradas.json
      command: ["python3", "-u", "loc-exporter.py"]


   simulator:
      container_name: bus_simulator
      image: python:3.7
      environment:
         - MONGO_URI=mongodb://mongo:27017/
         - LOC_SPAWN_INTERVAL=5
         - LOC_TTL=10
         - DRY_RUN=false
      volumes:
        - ./bus-sim.py:/bus-sim.py
        - ./locs.csv:/locs.csv
      command: ["python3", "-u", "bus-sim.py"]

  